[tool.poetry]
name = "llama-generation"
version = "0.1.0"
description = ""
authors = ["Fabio Gomez"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
